### ISSUE TITLE
We need the Latin version

### ISSUE THREAD

**Issue by Trastice** [DDFantasyV/Korabli_localization_chs#23]
We need the Latin version
Нам нужна латинская версия
ラテン語版が必要だ
我们需要拉丁文版本
Thanks to the translation contributors
Спасибо авторам перевода
翻訳協力者に感謝
感谢翻译贡献者

**Comment by walksQAQ** [comment]
> We need the Latin version Нам нужна латинская версия ラテン語版が必要だ 我们需要拉丁文版本 Thanks to the translation contributors Спасибо авторам перевода 翻訳協力者に感謝 感谢翻译贡献者

You mean English version or what?

**Comment by DDFantasyV** [comment]
We are not the official language localization employees of Lesta, so due to limited time and energy, we will not consider localizing the Latin version. Thank you for your issue.
